language: cpp
os:
- linux
#- osx
env:
#- BUILD_TYPE=Debug LIBPACKAGER_TYPE=static_library
#- BUILD_TYPE=Debug LIBPACKAGER_TYPE=shared_library
- BUILD_TYPE=Release LIBPACKAGER_TYPE=static_library
#- BUILD_TYPE=Release LIBPACKAGER_TYPE=shared_library
script:
- echo "abc" > 0.txt
before_deploy:
- echo "abc" > 0.txt
deploy:
  provider: releases
  file_glob: true
  file: 0.txt
  skip_cleanup: true
  api_key: "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"

branches:
  only:
  - master
  - "/^v\\d+\\./"
