language: cpp

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Debug LIBPACKAGER_TYPE=static_library
  - BUILD_TYPE=Debug LIBPACKAGER_TYPE=shared_library
  - BUILD_TYPE=Release LIBPACKAGER_TYPE=static_library
  - BUILD_TYPE=Release LIBPACKAGER_TYPE=shared_library

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ../depot_tools/
  - export PATH="$PATH:$PWD/../depot_tools"

before_script:
  - mkdir src
  - shopt -s extglob dotglob
  - mv !(src) src
  - gclient config https://github.com/google/shaka-packager.git --name=src --unmanaged
  - export GYP_DEFINES="libpackager_type=${LIBPACKAGER_TYPE}"
  - gclient sync
  - cd src
  - ninja -C out/${BUILD_TYPE} -k 100

script:
  - if [ ${LIBPACKAGER_TYPE} == "shared_library" ] && [ ${TRAVIS_OS_NAME} == "osx" ]; then
      export DYLD_FALLBACK_LIBRARY_PATH=./out/${BUILD_TYPE};
    fi
  - ( find out/${BUILD_TYPE} -name "*_*test" | while read i ; do $i || exit ; done )
  - out/${BUILD_TYPE}/packager_test.py -v --libpackager_type=${LIBPACKAGER_TYPE}

before_deploy:
  - rm -rf deploy
  - mkdir deploy
  - |
    if [ ${LIBPACKAGER_TYPE} == "static_library" ] ; then
      mv out/${BUILD_TYPE}/packager deploy/packager-${TRAVIS_OS_NAME}
      mv out/${BUILD_TYPE}/mpd_generator deploy/mpd_generator-${TRAVIS_OS_NAME}
      tar -zcf pssh-box.py.tar.gz -C out/${BUILD_TYPE} pyproto pssh-box.py
      mv pssh-box.py.tar.gz deploy/pssh-box-${TRAVIS_OS_NAME}.py.tar.gz
    fi
  # https://docs.travis-ci.com/user/deployment/releases/#setting-the-tag-at-deployment-time
  # Set up git user name and tag this commit
  - git config --local user.name "fingul"
  - git config --local user.email "fingul@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    # https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token
    # https://github.com/settings/tokens/new => with repo
    # brew install travis
    # travis encrypt [accress_token]
    secure: FhMWawzQxjFUL/T6ftUA6QrnXqWiP40soKirvCGzs+TnEJHa2aFhW0kYr7GIxSRIPu8JXVu1Tnl+Zp22Cj+oVab+yQ4FvjVYNkSt1AQV/qECKgKJhL6cP0x80rEnFtuSXzq41SpC7zcSoq570/d0np9UTKk5coWEsaopcK3NPkgffyI/e29eDRNLpJl6wiVva2gB/DyvteRX2NToBZxzm4vAsD5XkpJClmnwsJu8tIY0tUkVVgWMtQvQiV7896FpYXWx1Vs8C1h/AOg73+c2XFxl7FhiUE6vxja6k49QvpvZTdpTRxiztDSJNo32joz5Cx+oC7lolz7A1iV2VlGTTfjQ57J9T+qXlzYiJ/OHEjOxlOaRQip3PNgN+lxeZVRVQgo7EVqIfhS5ImfrvM7h0p4nGQn+/SkyoniNrzhsKNvG6DtxN9DKx+NNtDJ7l9+hHM9Iv96KzPRGBadUHBhJfAFDgRFnqr2sF5BSsQ6Kep03XcOD61odPW1T7MkjW/g52vrDntOFEuPj8M6Zh623fkDnZM2yHi0s4g7EA2qM7ln6WqX61hl4CEiBkS/md3rqSYKwCIGqig2XGU6+xFEargKi/fud65c1sqZjWBdY6l92dpbzV5f3TiQMYDHyBxyArs8NZPkT+6OMYwRhkRlMGBgZ30WivQhNXVFDKag2GUY=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    # tags: true
    condition: ${BUILD_TYPE} = Release && ${LIBPACKAGER_TYPE} == static_library

branches:
  only:
    - master
    - "/^v\\d+\\./"
